.TH "epylog-modules" "5" "0.9" "Konstantin Riabitsev" "Applications/System"

.SH NAME
\fBepylog-modules\fR \- epylog modules.

.SH SYNOPSIS
\fBepylog\fR uses pluggable modules to perform analysis and report on
syslog strings. 


.SH "AUTHORS"
.LP 
Konstantin Riabitsev <icon@phy.duke.edu>

.SH "SEE ALSO"
.LP 
epylog(8), epylog(3)

